app/Http/routes.php
<?php


Route::group(['middleware' => 'web'], function() {
    /**
     * Switch between the included languages
     */
    Route::group(['namespace' => 'Language'], function () {
        require (__DIR__ . '/Routes/Language/Language.php');
    });

    /**
     * Frontend Routes
     * Namespaces indicate folder structure
     */
    Route::group(['namespace' => 'Frontend'], function () {
        require (__DIR__ . '/Routes/Frontend/Frontend.php');
        require (__DIR__ . '/Routes/Frontend/Access.php');
    });



});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 * Admin middleware groups web, auth, and routeNeedsPermission
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    /**
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    require (__DIR__ . '/Routes/Backend/Dashboard.php');
    require (__DIR__ . '/Routes/Backend/Access.php');
    require (__DIR__ . '/Routes/Backend/LogViewer.php');
    require (__DIR__ . '/Routes/Backend/Eventos.php');
    require (__DIR__ . '/Routes/Backend/TipoEquipamento.php');
    require (__DIR__ . '/Routes/Backend/Armazens.php');
    require (__DIR__ . '/Routes/Backend/Equipamentos.php');
    require (__DIR__ . '/Routes/Backend/Stock.php');



});
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

app/Models/Evento/Area.php
<?php

namespace App\Models\Evento;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    //
}

app/Models/Evento/Evento.php
<?php

namespace App\Models\Evento;

use App\Models\Evento\Traits\Attribute\EventoAttribute;
use Illuminate\Database\Eloquent\Model;

class Evento extends Model
{
    use EventoAttribute;
    protected $guarded = array('id');

    public function user(){
        return $this->belongsToMany('App\Models\Access\User\User')->withTimestamps();
    }

    public function tipo_evento() {
        return $this->belongsTo('App\Models\Evento\TipoEvento', 'tipo_evento_id');
    }

    public function lugar() {
       return  $this->belongsTo('App\Models\Evento\Lugar','lugar_id');
    }

    public function owner()
    {
        return $this->belongsTo('App\Models\Access\User\User', 'owner_id', 'id');
    }

}

app/Models/Evento/Lugar.php
<?php

namespace App\Models\Evento;

use Illuminate\Database\Eloquent\Model;

class Lugar extends Model
{
    protected $table = 'lugares';
    protected $fillable =  ['nome', 'created_at', 'updated_at'];

    public function eventos(){
        return $this->hasMany('App\Models\Evento\Evento','lugar_id');
    }

}

app/Models/Evento/TipoEvento.php
<?php

namespace App\Models\Evento;

use Illuminate\Database\Eloquent\Model;

/**
 * Class TipoEvento
 * @package App\Models\Evento
 */
class TipoEvento extends Model
{
    protected $table = 'tipos_evento';

    public function eventos()
    {
        return $this->hasMany('App\Models\Evento\Evento', 'tipo_evento_id');
    }

}

app/Models/Evento/Traits/Attribute/EventoAttribute.php
<?php


namespace App\Models\Evento\Traits\Attribute;

/**
 * Created by PhpStorm.
 * User: nuno.silva
 * Date: 23-01-2016
 * Time: 20:13
 */
trait  EventoAttribute
{
    /**
     * @return bool
     */
    public function isConfirmado()
    {
        return $this->confirmado == 1;


    }

    public function isAtribuido()
    {
        return $this->atribuido == 1;
    }



    /**
     * @return string
     */
    public function getConfirmadoLabelAttribute()
    {
        if ($this->isConfirmado())
            return "<label class='label label-success' >Sim</label>";
        return "<label class='label label-danger'>Não</label>";
    }


    public function getAtribuidoLabelAttribute()
    {
        if ($this->isAtribuido())
            return "<label class='label label-success btn' id='la_".$this->id."' >Sim</label>";
        return "<label class='label label-danger'>Não</label>";
    }


    public function getViewButtonAttribute()
    {
        if (access()->allow('ver-eventos')) {
            return '

                    <a href="' . route('admin.eventos.evento.show', $this->id) . '" class="btn btn-xs btn-success"><i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.view') . '"></i></a>

                    ';
        }
    }


    public function getAttrButtonAttribute()
    {
        if (access()->allow('atribuir-evento')){
            return '
                    <span data-toggle="modal" data-target="#attr'.$this->id .'">
                    <a class="btn btn-xs bg-maroon"><i class="fa fa-users" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.attr') . '"></i></a>
                    </span>
                    ';
        }
    }




    public function getConfButtonAttribute()
    {
        switch ($this->confirmado) {
            case 0:
                if (access()->allow('confirmar-eventos')) {
                    return '<a href="' . route('admin.eventos.evento.conf', [$this->id, 1]) . '" class="btn btn-xs btn-info"><i class="fa fa-check-square" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.conf') . '"></i></a> ';
                }

                break;

            case 1:
                if (access()->allow('confirmar-eventos')) {
                    return '<a href="' . route('admin.eventos.evento.conf', [$this->id, 0]) . '" class="btn btn-xs btn-warning"><i class="fa fa-check-square-o" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.unconf') . '"></i></a> ';
                }

                break;

            default:
                return '';
            // No break
        }

        return '';

    }



    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        if (access()->allow('editar-eventos')) {
            return '<a href="' . route('admin.eventos.evento.edit', $this->id) . '" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a> ';
        }

        return '';
    }

    public function getDeleteButtonAttribute()
    {
        if (access()->allow('apagar-eventos')) {
            return '<a href="' . route('admin.eventos.evento.destroy', $this->id) . '" data-method="delete" class="btn btn-xs btn-danger"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.delete') . '"></i></a> ';
        }

        return '';
    }

    public function getAutoButtonAttribute()
    {
        if (access()->allow('auto-atribuir')) {
            if(!$this->isAtribuido()) {
                return '<a href="' . route('admin.eventos.evento.autoattr', $this->id) . '" class="btn btn-xs bg-teal"><i class="fa fa-user" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.auto') . '"></i></a> ';
            }
        }


        return '';
    }

}

app/Http/Controllers/Backend/Evento/EventoController.php
<?php
/**
 * Created by PhpStorm.
 * User: nuno.silva
 * Date: 17-01-2016
 * Time: 17:57
 */

namespace App\Http\Controllers\Backend\Evento;

use App\Events\Backend\Evento\NovoEvento;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Evento\EventoContract;
use App\Repositories\Backend\Lugar\LugarContract;
use App\Repositories\Backend\TipoEvento\TipoEventoContract;
use App\Repositories\Backend\User\UserContract;
use Illuminate\Http\Request;
use App\Models\Evento\Evento;
use App\Models\Access\User\User;
use App\Http\Emails\Evento\EventoEmail;
use Carbon\Carbon;
use Event;
use App\Events\Backend\Evento\EventoAtribuido;
use PHPushbullet\PHPushbullet;


/**
 * Class EventoController
 * @package App\Http\Controllers\Backend\Evento
 */
class EventoController extends Controller
{


    /**
     * @param EventoContract $eventos
     */
    public function __construct(
        EventoContract $eventos,
        LugarContract $lugares,
        TipoEventoContract $tipo,
        UserContract $users
    )
    {
      $this->eventos = $eventos;
      $this->lugares = $lugares;
      $this->tipo = $tipo;
      $this->users = $users;
      Carbon::setLocale('pt');

    }


    /**
     *
     */
    public function index()
    {

        if (access()->hasRoles([1,3,5])) {
            return view('backend.evento.evento.index')->withEventos($this->eventos->getAllEventos())
                ->withUsers($this->users->getAllUsers('name', 'asc')->lists('name', 'id'));
        }
        return redirect()->route('admin.eventos.evento.meus');

    }

    /**
     * @return mixed
     */
    public function meusEventos()
    {
        return view('backend.evento.evento.meus')->withEventos($this->eventos->getMeusEventos())
                                                  ->withUsers($this->users->getAllUsers('name','asc')->lists('name','id'));

    }


    public function eventosAttr(){
        return view('backend.evento.evento.atribuidos')->withEventos($this->eventos->getEventosAtribuidos())
                                                    ->withUsers($this->users->getAllUsers('name', 'asc')->lists('name','id'));
    }

    public function PorAtribuir(){
        return view('backend.evento.evento.poratribuir')->withEventos($this->eventos->getEventosPorAtribuir())
                                                    ->withUsers($this->users->getAllUsers('name','asc')->lists('name','id'));
    }


    public function usersAttr($id){
        return $this->eventos->getUsersAttr($id)->lists('name','email','id');
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backend.evento.evento.create')
            ->withLugares($this->lugares->getAllLugares()->lists('nome','id'))
            ->withTipo($this->tipo->getAllTipoEvento()->lists('tipo_evento','id'));
    }


    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {

        if($this->eventos->create($request)) {
            if (access()->allow('listar-eventos'))
                return redirect()->route('admin.eventos.evento.index')->withFlashSuccess(trans('alerts.backend.eventos.evento.created'));
            return redirect()->route('admin.eventos.evento.meus')->withFlashSuccess(trans('alerts.backend.eventos.evento.created'));
        }else {
            return redirect()->back()->withFlashDanger('Erro ao guardar o evento, contacte o administrador');
        }
    }

    /**
     * @param $id
     * @param Request $request
     * @return mixed
     */
    public function edit($id, Request $request)
   {
       $evento = $this->eventos->findOrThrowException($id, true);
       $nec = explode(':',$evento->tipo_necessidade);

       return view('backend.evento.evento.edit')
           ->withEvento($evento)
           ->withLugares($this->lugares->getAllLugares()->lists('nome','id'))
           ->withTipo($this->tipo->getAllTipoEvento()->lists('tipo_evento','id'))
           ->withNec($nec);
   }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $temp = $request->input('tipo_necessidade');
        $input['tipo_necessidade'] = implode(':',$temp);
        $this->eventos->update($input,$id);
        return redirect()->route('admin.eventos.evento.index')->withFlashSuccess(trans('alerts.backend.eventos.evento.updated'));
    }

    /**
     * @param $id
     * @param Request $request
     * @return mixed
     */
    public function destroy($id, Request $request)
    {
        $this->eventos->delete($id);
        return redirect()->back()->withFlashSuccess(trans('alerts.backend.eventos.evento.deleted'));
    }




    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        $evento = $this->eventos->findOrThrowException($id);
        $nec = explode(':',$evento->tipo_necessidade);

        return view('backend.evento.evento.view')
            ->withEvento($evento)
            ->withLugares($this->lugares->getAllLugares()->lists('nome','id'))
            ->withTipo($this->tipo->getAllTipoEvento()->lists('tipo_evento','id'))
            ->withNec($nec);

    }

    /**
     * @return bool
     */
    public function calendario(){
        $events = [];
        $eventos = $this->eventos->getAllEventos();
        foreach($eventos as $evento)
        {
            $events[] = \Calendar::event(
                $evento->tipo_evento->tipo_evento,
                false,
                new \DateTime($evento->dia.$evento->hora_inicio),
                new \DateTime($evento->dia.$evento->hora_fim),
                $evento->id,
                [
                    'description' => $evento->lugar->nome
                ]
            );
        }

        $calendar = \Calendar::addEvents($events) //add an array with addEvents
        ->setOptions([ //set fullcalendar options
            'firstDay' => 1
        ]);
        return view('backend.evento.evento.calendario',['calendar' => $calendar]);
    }


    /**
     * @param $id
     * @param $status
     * @return mixed
     */
    public function conf($id, $status)
    {
        $this->eventos->conf($id, $status);
        return redirect()->back()->withFlashSuccess(trans('alerts.backend.eventos.evento.updated'));
    }

    /**
     * @param Request $request
     * @return int
     */
    public function postAttr(Request $request){
        if($request->ajax()) {

           $evento = Evento::find($request->input('id'));
            foreach ($request->users as $user){
                $users[$user] = $user;

            }
          if($evento->user()->sync($users)){
            event::fire(new EventoAtribuido($evento, $users));
              $this->eventos->atribuir($evento->id);
          }

        }
    }

    public function autoAtribuir($id){
        $evento = Evento::find($id);
        $user = array(access()->id());
        if($evento->user()->sync($user)){
            event::fire(new EventoAtribuido($evento, $user));
            $this->eventos->atribuir($evento->id);
            return redirect()->back()->withFlashSuccess(trans('alerts.backend.eventos.evento.updated'));
        }


    }



}

app/Http/Controllers/Backend/Evento/LugarController.php
<?php

namespace App\Http\Controllers\Backend\Evento;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Lugar\LugarContract;
use App\DataTables\LugarDataTable;
use Illuminate\Http\Request;
Use Flash;

class LugarController extends Controller
{
    public function __construct (LugarContract $lugares)
    {
        $this->lugares = $lugares;
    }

    public function index(LugarDataTable $lugarDataTable)
    {
        return $lugarDataTable->render('backend.evento.local.index');
    }

    public function create()
    {
        return view('backend.evento.local.create');
    }

    public function store(Request $request)
    {
        $input = $request->all();

        $lugar = $this->lugares->create($input);

        Flash::success('Armazém guardado com sucesso.');

        return redirect(route('admin.eventos.local.index'));
    }

    public function show($id)
    {
        $lugar = $this->lugares->findOrThrowException($id);

        if (empty($lugar)) {
            Flash::error('Local não encontrado');

            return redirect(route('admin.eventos.local.index'));
        }

        return view('backend.evento.local.show')->with('lugar', $lugar);
    }

    public function edit($id)
    {
        $lugar = $this->lugares->findOrThrowException($id);

        if (empty($lugar)) {
            Flash::error('Local não encontrado');

            return redirect(route('admin.eventos.local.index'));
        }

        return view('backend.evento.local.edit')->with('lugar', $lugar);
    }

    public function update($id, Request $request)
    {
      $lugar = $this->lugares->findOrThrowException($id);

        if (empty($lugar)) {
            Flash::error('Local não encontrado');

            return redirect(route('admin.eventos.local.index'));
        }

        $lugar = $this->lugares->update($id, $request->all());

        Flash::success('Local actualizado com sucesso.');

        return redirect(route('admin.eventos.local.index'));
    }

    public function destroy($id)
    {
        $lugar = $this->lugares->findOrThrowException($id);

        if (empty($lugar)) {
            Flash::error('Local não encontrado');

            return redirect(route('admin.eventos.local.index'));
        }

        $this->lugares->delete($id);

        Flash::success('Local apagado com sucesso.');

        return redirect(route('admin.eventos.local.index'));
    }
}

resources/views/backend/evento/evento/atribuidos.blade.php
@extends ('backend.layouts.master')

@section ('title', trans('labels.backend.eventos.evento.gestao'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.eventos.evento.gestao') }}
        <small>{{ trans('labels.backend.eventos.evento.meus') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box">


            <!-- Nav tabs --><ul class="nav nav-pills" role="tablist">
            <li role="presentation" id="meus" ><a href="meus" aria-controls="meus" ><h4><i class="fa fa-user"></i> Meus Eventos</h4></a></li>
            @roles([1,3,5])
            <li role="presentation" id="atribuidos" class="active"><a href="atribuidos" aria-controls="atribuidos" ><h4><i class="fa fa-arrow-circle-right"></i> Atribuidos a mim</h4></a></li>
            <li role="presentation" id="por_atribuir" ><a href="poratribuir" aria-controls="por_atribuir" ><h4><i class="fa fa-question-circle"></i> Por atribuir</h4></a></li>

            @endauth
        </ul>

            <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="meus">
                <div class="box-body">
                    @if(isset($eventos))
                        <div class="table-responsive">
                            <table class="text-center table table-striped table-bordered table-hover" id="dados">
                                <thead>
                                <tr>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.owner') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.titulo') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.data') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.lugar') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.tipo') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.atribuido') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.confirmado') }}</th>
                                    <th>{{ trans('labels.general.actions') }}</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach ($eventos as $evento)

                                    <tr>
                                        <td>{!! $evento->owner->name !!}</td>
                                        <td>{!! $evento->titulo !!}</td>
                                        <td>{!! $evento->dia !!}</td>
                                        <td>{!! $evento->lugar->nome !!}</td>
                                        <td>{!! $evento->tipo_evento->tipo_evento !!}</td>
                                        <td>{!! $evento->atribuido_label !!}</td>
                                        <td>{!! $evento->confirmado_label !!}</td>
                                        <td>{!! $evento->view_button !!}{!! $evento->edit_button !!}{!! $evento->delete_button !!} {!! $evento->conf_button !!} {!! $evento->attr_button !!} {!! $evento->auto_button !!}</td>
                                        @roles([1,3,5])
                                        @include('backend.evento.evento.attr')
                                        @endauth
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <h2>Sem Eventos</h2>
                    @endif

                    <div class="pull-left">

                    </div>

                    <div class="pull-right">

                    </div>

                    <div class="clearfix"></div>
                </div><!-- /.box-body -->
            </div>
            @role('Administrator')

            @endauth

        </div>


    </div><!--box-->





{!! Html::script('js/backend/attr.js') !!}

@stop

resources/views/backend/evento/evento/attr_user.blade.php
<script type="text/javascript">

    $(document).ready(function(){

        $('#la_{{$evento->id}}').click(function(){
            $.get("{{$evento->id}}/usersAttr",function(data) {
                console.log(data);
                var array = [];
                for(i in data) {
                    array.push(data[i]);
                }
                var vals = (array.join(", "));
                $('#la_{{$evento->id}}').popover({
                    title: "Atribuido a:",
                    content: vals

                });
                $('#la_{{$evento->id}}').popover("show");
            });
        });


    });
</script>

resources/views/backend/evento/evento/calendario.blade.php
@extends('backend.layouts.master')
@section('content')
    {!! $calendar->calendar() !!}
    {!! $calendar->script() !!}
    @endsection

resources/views/backend/evento/evento/index.blade.php
@extends ('backend.layouts.master')

@section ('title', trans('labels.backend.eventos.evento.gestao'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.eventos.evento.gestao') }}
        <small>{{ trans('labels.backend.eventos.evento.todos') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.eventos.evento.todos') }}</h3>

            <div class="box-tools pull-right">
                {{-- @include('backend.access.includes.partials.header-buttons')--}}
            </div>
        </div><!-- /.box-header -->

        <div class="box-body">
            @if(isset($eventos))
            <div class="table-responsive">
                <table class="text-center table table-striped table-bordered table-hover" id="dados">
                    <thead>
                    <tr>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.owner') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.titulo') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.data') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.lugar') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.tipo') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.atribuido') }}</th>
                        <th>{{ trans('labels.backend.eventos.evento.tabela.confirmado') }}</th>
                        <th>{{ trans('labels.general.actions') }}</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach ($eventos as $evento)

                        <tr>
                            <td>{!! $evento->owner->name !!}</td>
                            <td>{!! $evento->titulo !!}</td>
                            <td>{!! $evento->dia !!}</td>
                            <td>{!! $evento->lugar->nome !!}</td>
                            <td>{!! $evento->tipo_evento->tipo_evento !!}</td>
                            <td>{!! $evento->atribuido_label !!}</td>
                            <td>{!! $evento->confirmado_label !!}</td>
                            <td>{!! $evento->view_button !!}{!! $evento->edit_button !!}{!! $evento->delete_button !!} {!! $evento->conf_button !!} {!! $evento->attr_button !!} {!! $evento->auto_button !!}</td>
                            @include('backend.evento.evento.all_attr')

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            @else
                <h2>Sem Eventos</h2>
                @endif

            <div class="pull-left">

            </div>

            <div class="pull-right">

            </div>

            <div class="clearfix"></div>
        </div><!-- /.box-body -->
    </div><!--box-->

{!! Html::script('js/backend/attr.js') !!}

@stop

resources/views/backend/evento/evento/meus.blade.php
@extends ('backend.layouts.master')

@section ('title', trans('labels.backend.eventos.evento.gestao'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.eventos.evento.gestao') }}
        <small>{{ trans('labels.backend.eventos.evento.meus') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box">


            <!-- Nav tabs -->
        <ul class="nav nav-pills" role="tablist">
            <li role="presentation" id="meus" class="active"><a href="meus" aria-controls="meus" ><h4><i class="fa fa-user"></i> Meus Eventos</h4></a></li>
            @roles([1,3,5])
            <li role="presentation" id="atribuidos"><a href="atribuidos" aria-controls="atribuidos" ><h4><i class="fa fa-arrow-circle-right"></i> Atribuidos a mim</h4></a></li>
            <li role="presentation" id="por_atribuir" ><a href="poratribuir" aria-controls="por_atribuir" ><h4><i class="fa fa-question-circle"></i> Por atribuir</h4></a></li>

            @endauth
        </ul>

            <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="meus">
                <div class="box-body">
                    @if(isset($eventos))
                        <div class="table-responsive">
                            <table class="text-center table table-striped table-bordered table-hover" id="dados">
                                <thead>
                                <tr>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.owner') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.titulo') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.data') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.lugar') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.tipo') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.atribuido') }}</th>
                                    <th>{{ trans('labels.backend.eventos.evento.tabela.confirmado') }}</th>
                                    <th>{{ trans('labels.general.actions') }}</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach ($eventos as $evento)

                                    <tr>
                                        <td>{!! $evento->owner->name !!}</td>
                                        <td>{!! $evento->titulo !!}</td>
                                        <td>{!! $evento->dia !!}</td>
                                        <td>{!! $evento->lugar->nome !!}</td>
                                        <td>{!! $evento->tipo_evento->tipo_evento !!}</td>
                                        <td>{!! $evento->atribuido_label !!}</td>
                                        <td>{!! $evento->confirmado_label !!}</td>
                                        <td>{!! $evento->view_button !!}{!! $evento->edit_button !!}{!! $evento->delete_button !!} {!! $evento->conf_button !!} {!! $evento->attr_button !!} {!! $evento->auto_button !!}</td>
                                        @roles([1,3,5])
                                        @include('backend.evento.evento.attr')
                                        @endauth
                                        @role(4)
                                        @include('backend.evento.evento.attr_user')
                                        @endauth
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <h2>Sem Eventos</h2>
                    @endif

                    <div class="pull-left">

                    </div>

                    <div class="pull-right">

                    </div>

                    <div class="clearfix"></div>
                </div><!-- /.box-body -->
            </div>
            @role('Administrator')

            @endauth

        </div>


    </div><!--box-->



{!! Html::script('js/backend/attr.js') !!}

@stop